# Generated by Django 4.0.3 on 2022-04-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tickets', '0002_alter_ticket_it_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='it_assigned',
        ),
        migrations.CreateModel(
            name='TicketIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('it_assigned', models.ForeignKey(blank=True, limit_choices_to={'is_it': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_for_ticket', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tickets.ticket')),
            ],
        ),
    ]
