# Generated by Django 4.0.3 on 2022-04-22 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tickets', '0003_remove_ticket_it_assigned_ticketit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='it_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='it_for_ticket', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TicketIT',
        ),
    ]
